package com.cmput401f17.eplscavengerhunt.custom;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.os.Environment;
import android.provider.MediaStore;
import android.support.v4.content.FileProvider;

import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;


/**
 * Class that has the task of Requesting the device's system Camera app for a photo
 */
public class CameraHandler {
    private File image;
    private Context context;

    public CameraHandler(Context context) {
        this.context = context;
    }

    /**
     * Sends intent to system camera for a photo If an image file
     * has been successfully generated by generateImage.
     * https://developer.android.com/training/camera/photobasics.html
     * @param requestImageCapture, the activity's constant for REQUEST_IMAGE_CAPTURE
     * @return image instance.
     */
    public File dispatchTakePictureIntent(int requestImageCapture) {
        Intent takePictureIntent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
        if (takePictureIntent.resolveActivity(context.getPackageManager()) != null) {
            // Create the File where the photo should go
            try {
                image = generateImage();
            } catch (IOException ex) {
                // Error occurred while creating the File
            }
            if (image != null) {
                Uri photoURI = FileProvider.getUriForFile(context,
                        "com.cmput401f17.fileprovider",
                        image);
                takePictureIntent.putExtra(MediaStore.EXTRA_OUTPUT, photoURI);
                ((Activity)context).startActivityForResult(takePictureIntent, requestImageCapture);
            }
        }
        return image;
    }

    /**
     * Generates an image instance which has an empty image file.
     * referenced from https://developer.android.com/training/camera/photobasics.html
     * accessed 10-24-2017
     */
    private File generateImage() throws IOException {
        // Create an image file name
        String timeStamp = new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date());
        String imageFileName = "JPEG_" + timeStamp + "_";
        File storageDir = context.getExternalFilesDir(Environment.DIRECTORY_PICTURES);
        File image = File.createTempFile(
                imageFileName,  /* prefix */
                ".jpg",         /* suffix */
                storageDir      /* directory */
        );
        return image;
    }
}
